### ISSUE TITLE
Link to Github file for other languages does not work

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField-docs#350]
@m-kuhn I just found an issue.

## Steps to reproduce

- Access to https://docs.qfield.org/ja/success-stories/heritage-impact-assessment/
- Click pencil (edit) button to open the relevant Github's file page
- Browser returns 404 error because it is accessing `heritage-impact-assessment.ja.md` file.
https://github.com/opengisch/qfield-docs/tree/master/documentation/success-stories/heritage-impact-assessment.ja.md

## Expected behavior

If selected language is not English, should the link be for original `en` file? In this case, it should open `heritage-impact-assessment.en.md` file.

I am not sure whether this issue can be solved in mkdocs.

**Comment by m-kuhn** [comment]
@why-not-try-calmer could you have a look if this is a simple fix?

**Comment by why-not-try-calmer** [comment]
The pencil (edit) button denotes a functionality for editing the source from a WYSIWYG context, as the editor in Wordpress or Wikipedia. Since translations are injected into templates when building the web site, there is no 1-1 relation between web pages and editable sources. So my suggestion would be to have the pencil button always point to the Issues section of the repository.
